name: Build ForceX86Exec Kext

on:
  push:
    paths:
      - 'ForceX86Exec/**'
  workflow_dispatch:

jobs:
  build-kext:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lilu & MacKernelSDK
        run: |
          git clone --depth 1 https://github.com/acidanthera/Lilu.git
          git clone --depth 1 https://github.com/acidanthera/MacKernelSDK.git

      - name: Compile ForceX86Exec Kext
        run: |
          mkdir -p ForceX86Exec.kext/Contents/MacOS
          cp ForceX86Exec/Info.plist ForceX86Exec.kext/Contents/

          clang++ -O2 -std=c++17 -nostdinc++ \
            -DPRODUCT_NAME=ForceX86Exec \
            -I. -ILilu -ILilu/Lilu -IMacKernelSDK/Headers -IMacKernelSDK/SDK/usr/include \
            -isysroot $(xcrun --show-sdk-path) \
            -target x86_64-apple-macos10.13 \
            -mkernel -fno-builtin -fno-exceptions -fno-rtti -fno-use-cxa-atexit \
            -Xlinker -kext \
            ForceX86Exec/ForceX86Exec.cpp \
            -o ForceX86Exec.kext/Contents/MacOS/ForceX86Exec

      - name: Move Kext to Payloads
        run: |
          mkdir -p payloads/Kexts/Acidanthera
          rm -rf payloads/Kexts/Acidanthera/ForceX86Exec.kext
          cp -R ForceX86Exec.kext payloads/Kexts/Acidanthera/

      - name: Commit Compiled Kext
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add payloads/Kexts/Acidanthera/ForceX86Exec.kext
          git commit -m "Auto-build : Génération binaire ForceX86Exec.kext" || exit 0
          git push
